update 2.1.4

diff --git a/.github/workflows/build-macos-installers.yml b/.github/workflows/build-macos-installers.yml
--- a/.github/workflows/build-macos-installers.yml
+++ b/.github/workflows/build-macos-installers.yml
@@ -42,30 +42,25 @@ jobs:
     name: Build ${{ matrix.os.name }} DMG
     runs-on: ${{ matrix.os.runs-on }}
     timeout-minutes: 90
+    outputs:
+      chik-installer-version: ${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}
     strategy:
       fail-fast: false
-      max-parallel: 4
       matrix:
         python-version: ["3.10"]
         os:
           - runs-on: macos-11
             name: intel
-            file-suffix: ""
-            mac-package-name: "Chik-darwin-x64"
-            glue-name: "build-macos"
             bladebit-suffix: macos-x86-64.tar.gz
 #          - runs-on: [MacOS, ARM64]
 #            name: m1
-#            file-suffix: "-arm64"
-#            mac-package-name: "Chik-darwin-arm64"
-#            glue-name: "build-mac-m1"
 #            bladebit-suffix: macos-arm64.tar.gz
 
     steps:
       - uses: Chik-Network/actions/clean-workspace@main
 
       - name: Checkout Code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
           submodules: recursive
@@ -99,21 +94,11 @@ jobs:
         shell: bash
         run: |
           unset HAS_APPLE_SECRET
-          unset HAS_AWS_SECRET
-          unset HAS_GLUE_SECRET
 
           if [ -n "$APPLE_SECRET" ]; then HAS_APPLE_SECRET='true' ; fi
           echo HAS_APPLE_SECRET=${HAS_APPLE_SECRET} >> "$GITHUB_OUTPUT"
-
-          if [ -n "$AWS_SECRET" ]; then HAS_AWS_SECRET='true' ; fi
-          echo HAS_AWS_SECRET=${HAS_AWS_SECRET} >> "$GITHUB_OUTPUT"
-
-          if [ -n "$GLUE_ACCESS_TOKEN" ]; then HAS_GLUE_SECRET='true' ; fi
-          echo HAS_GLUE_SECRET=${HAS_GLUE_SECRET} >> "$GITHUB_OUTPUT"
         env:
           APPLE_SECRET: "${{ secrets.APPLE_DEV_ID_APP }}"
-          AWS_SECRET: "${{ secrets.CHIK_AWS_ACCOUNT_ID }}"
-          GLUE_ACCESS_TOKEN: "${{ secrets.GLUE_ACCESS_TOKEN }}"
 
       - name: Create installer version number
         id: version_number
@@ -128,7 +113,6 @@ jobs:
         uses: Chik-Network/actions/setup-python@main
         with:
           python-version: ${{ matrix.python-version }}
-          force-pyenv: 'true'
 
       # This will be recreated in the next step
       # Done now and at the end of the workflow in case the last workflow fails, and this is still around
@@ -200,11 +184,12 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
           development: true
+          constraints-file-artifact-name: constraints-file-${{ matrix.os.name }}
 
       - uses: chik-network/actions/activate-venv@main
 
       - name: Setup Node 18.x
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: '18.x'
 
@@ -250,6 +235,91 @@ jobs:
           name: chik-installers-macos-dmg-${{ matrix.os.name }}
           path: ${{ github.workspace }}/build_scripts/final_installer/
 
+      - name: Remove working files to exclude from cache
+        run: |
+          rm -rf ./chik-blockchain-gui/packages/gui/daemon
+
+      # We want to delete this no matter what happened in the previous steps (failures, success, etc)
+      - name: Delete signing keychain
+        if: always()
+        run:
+          security delete-keychain signing_temp.keychain || true
+
+  publish:
+    name: Publish ${{ matrix.os.name }} DMG
+    runs-on: ${{ matrix.os.runs-on }}
+    needs:
+    - build
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ["3.10"]
+        os:
+          - runs-on: macos-11
+            name: intel
+            file-suffix: ""
+            glue-name: "build-macos"
+          - runs-on: [MacOS, ARM64]
+            name: m1
+            file-suffix: "-arm64"
+            glue-name: "build-mac-m1"
+
+    env:
+      CHIK_INSTALLER_VERSION: ${{ needs.build.outputs.chik-installer-version }}
+
+    steps:
+      - uses: Chik-Network/actions/clean-workspace@main
+
+      - name: Setup Python environment
+        uses: Chik-Network/actions/setup-python@main
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - uses: chik-network/actions/create-venv@main
+        id: create-venv
+
+      - uses: chik-network/actions/activate-venv@main
+        with:
+          directories: ${{ steps.create-venv.outputs.activate-venv-directories }}
+
+      - name: Download constraints file
+        uses: actions/download-artifact@v3
+        with:
+          name: constraints-file-${{ matrix.os.name }}
+          path: venv
+
+      - name: Install utilities
+        run: |
+          pip install --constraint venv/constraints.txt py3createtorrent
+
+      - name: Download packages
+        uses: actions/download-artifact@v3
+        with:
+          name: chik-installers-macos-dmg-${{ matrix.os.name }}
+          path: build_scripts/final_installer/
+
+      - name: Set Env
+        uses: Chik-Network/actions/setjobenv@main
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Test for secrets access
+        id: check_secrets
+        shell: bash
+        run: |
+          unset HAS_AWS_SECRET
+          unset HAS_GLUE_SECRET
+
+          if [ -n "$AWS_SECRET" ]; then HAS_AWS_SECRET='true' ; fi
+          echo HAS_AWS_SECRET=${HAS_AWS_SECRET} >> "$GITHUB_OUTPUT"
+
+          if [ -n "$GLUE_API_URL" ]; then HAS_GLUE_SECRET='true' ; fi
+          echo HAS_GLUE_SECRET=${HAS_GLUE_SECRET} >> "$GITHUB_OUTPUT"
+        env:
+          AWS_SECRET: "${{ secrets.CHIK_AWS_ACCOUNT_ID }}"
+          GLUE_API_URL: "${{ secrets.GLUE_API_URL }}"
+
       - name: Install AWS CLI
         if: steps.check_secrets.outputs.HAS_AWS_SECRET
         run: |
@@ -262,78 +332,67 @@ jobs:
       - name: Create Checksums
         run: |
           ls
-          shasum -a 256 ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg > ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256
+          shasum -a 256 ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg > ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256
 
       - name: Configure AWS credentials
         if: steps.check_secrets.outputs.HAS_AWS_SECRET
-        uses: aws-actions/configure-aws-credentials@v2
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::${{ secrets.CHIK_AWS_ACCOUNT_ID }}:role/installer-upload
           aws-region: us-west-2
 
       - name: Upload to s3
         if: steps.check_secrets.outputs.HAS_AWS_SECRET
-        env:
-          CHIK_INSTALLER_VERSION: ${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}
         run: |
           GIT_SHORT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-8)
           CHIK_DEV_BUILD=${CHIK_INSTALLER_VERSION}-$GIT_SHORT_HASH
           echo "CHIK_DEV_BUILD=$CHIK_DEV_BUILD" >> "$GITHUB_ENV"
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.chiknetwork.com/dev/Chik-${CHIK_DEV_BUILD}${{ matrix.os.file-suffix }}.dmg
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.chiknetwork.com/dev/Chik-${CHIK_DEV_BUILD}${{ matrix.os.file-suffix }}.dmg
 
       - name: Create torrent
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         if: env.FULL_RELEASE == 'true'
         run: |
-          py3createtorrent -f -t udp://tracker.opentrackr.org:1337/announce ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg -o ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent --webseed https://download.chiknetwork.com/install/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg
+          py3createtorrent -f -t udp://tracker.opentrackr.org:1337/announce ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg -o ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent --webseed https://download.chiknetwork.com/install/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg
           ls ${{ github.workspace }}/build_scripts/final_installer/
-          gh release upload $RELEASE_TAG ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent
+          gh release upload --repo ${{ github.repository }} $RELEASE_TAG ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent
 
       - name: Upload Dev Installer
         if: steps.check_secrets.outputs.HAS_AWS_SECRET && github.ref == 'refs/heads/main'
-        env:
-          CHIK_INSTALLER_VERSION: ${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}
         run: |
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.chiknetwork.com/latest-dev/Chik${{ matrix.os.file-suffix }}_latest_dev.dmg
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256 s3://download.chiknetwork.com/latest-dev/Chik${{ matrix.os.file-suffix }}_latest_dev.dmg.sha256
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.chiknetwork.com/latest-dev/Chik${{ matrix.os.file-suffix }}_latest_dev.dmg
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256 s3://download.chiknetwork.com/latest-dev/Chik${{ matrix.os.file-suffix }}_latest_dev.dmg.sha256
 
       - name: Upload Release Files
         if: steps.check_secrets.outputs.HAS_AWS_SECRET && env.FULL_RELEASE == 'true'
         run: |
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.chiknetwork.com/install/
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256 s3://download.chiknetwork.com/install/
-          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent s3://download.chiknetwork.com/torrents/
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg s3://download.chiknetwork.com/install/
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.sha256 s3://download.chiknetwork.com/install/
+          aws s3 cp ${{ github.workspace }}/build_scripts/final_installer/Chik-${{ env.CHIK_INSTALLER_VERSION }}${{ matrix.os.file-suffix }}.dmg.torrent s3://download.chiknetwork.com/torrents/
 
       - name: Upload release artifacts
         if: env.RELEASE == 'true'
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          CHIK_INSTALLER_VERSION: ${{ steps.version_number.outputs.CHIK_INSTALLER_VERSION }}
         run: |
           gh release upload \
+            --repo ${{ github.repository }} \
             $RELEASE_TAG \
             build_scripts/final_installer/*.dmg
+
+      - uses: Chik-Network/actions/github/jwt@main
+        if: steps.check_secrets.outputs.HAS_GLUE_SECRET
 
       - name: Mark pre-release installer complete
         if: steps.check_secrets.outputs.HAS_GLUE_SECRET && env.PRE_RELEASE == 'true'
         run: |
-          curl -s -XPOST -H "Authorization: Bearer ${{ secrets.GLUE_ACCESS_TOKEN }}" --data '{"chik_ref": "${{ env.RELEASE_TAG }}"}' ${{ secrets.GLUE_API_URL }}/api/v1/${{ env.RFC_REPO }}-prerelease/${{ env.RELEASE_TAG }}/success/${{ matrix.os.glue-name }}
+          curl -s -XPOST -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" --data '{"chik_ref": "${{ env.RELEASE_TAG }}"}' ${{ secrets.GLUE_API_URL }}/api/v1/${{ env.RFC_REPO }}-prerelease/${{ env.RELEASE_TAG }}/success/${{ matrix.os.glue-name }}
 
       - name: Mark release installer complete
         if: steps.check_secrets.outputs.HAS_GLUE_SECRET && env.FULL_RELEASE == 'true'
         run: |
-          curl -s -XPOST -H "Authorization: Bearer ${{ secrets.GLUE_ACCESS_TOKEN }}" --data '{"chik_ref": "${{ env.RELEASE_TAG }}"}' ${{ secrets.GLUE_API_URL }}/api/v1/${{ env.RFC_REPO }}/${{ env.RELEASE_TAG }}/success/${{ matrix.os.glue-name }}
-
-      # We want to delete this no matter what happened in the previous steps (failures, success, etc)
-      - name: Delete signing keychain
-        if: always()
-        run:
-          security delete-keychain signing_temp.keychain || true
-
-      - name: Remove working files to exclude from cache
-        run: |
-          rm -rf ./chik-blockchain-gui/packages/gui/daemon
+          curl -s -XPOST -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" --data '{"chik_ref": "${{ env.RELEASE_TAG }}"}' ${{ secrets.GLUE_API_URL }}/api/v1/${{ env.RFC_REPO }}/${{ env.RELEASE_TAG }}/success/${{ matrix.os.glue-name }}
 
   test:
     name: Test ${{ matrix.os.name }} ${{ matrix.arch.name }}
@@ -398,4 +457,4 @@ jobs:
     - name: Detach .dmg
       if: always()
       run: |
-        hdiutil detach "/Volumes/Chik "*
+        hdiutil detach -force "/Volumes/Chik "*
